const { db } = require("../db-config");
const { getCards } = require("../movies/getCards");
const { getCategories } = require("../movies/getCategories");
const { getMovieDetails } = require("../movies/getMovieDetails");
const { postComment } = require("../movies/postComment");
const { getComments } = require("../movies/getComments");
const { getEachComment } = require("../movies/getEachComment");
const { getReactions } = require("../movies/getReactions");
const { addReaction } = require("../movies/addReaction");
const { updateReaction } = require("../movies/updateReaction");
const { getLikes } = require("../movies/getLikes");
const { addFeedback } = require("../movies/addFeedback");
const { updateFeedback } = require("../movies/updateFeedback");
const { deleteComment } = require("../movies/deleteComment");
const { addFavourite } = require("../movies/addFavourite");
const { getFavourites } = require("../movies/getFavourites");
const { deleteFavourite } = require("../movies/deleteFavourite");
const { getMoviesByCategory } = require("../movies/getMoviesByCategory");
const { filterFavourites } = require("../movies/filterFavourites");
const { searchMovies } = require("../movies/searchMovies");
const { getMyList } = require("../movies/getMyList");
const { addMyList } = require("../movies/addMyList");
const { deleteFromList } = require("../movies/deleteFromList");
const { filterMyList } = require("../movies/filterMyList");

const express = require("express");
const moviesRouter = express.Router();

getCards(moviesRouter, db);
getCategories(moviesRouter, db);
getMovieDetails(moviesRouter, db);
postComment(moviesRouter, db);
getComments(moviesRouter, db);
getEachComment(moviesRouter, db);
getFavourites(moviesRouter, db);
getReactions(moviesRouter, db);
addReaction(moviesRouter, db);
updateReaction(moviesRouter, db);
getLikes(moviesRouter, db);
addFeedback(moviesRouter, db);
updateFeedback(moviesRouter, db);
deleteComment(moviesRouter, db);
addFavourite(moviesRouter, db);
deleteFavourite(moviesRouter, db);
getMoviesByCategory(moviesRouter, db);
filterFavourites(moviesRouter, db);
searchMovies(moviesRouter, db);
getMyList(moviesRouter, db);
addMyList(moviesRouter, db);
deleteFromList(moviesRouter, db);
filterMyList(moviesRouter, db);

exports.moviesRouter = moviesRouter;